### ISSUE TITLE
Opro_enhancer link not working

### ISSUE THREAD

**Issue by Yujun-Zou** [YiVal/YiVal#194]
https://colab.research.google.com/drive/1QTS3iMwQ5bOEgKDn5DrlmZ6V0rh5APdA?usp=sharing

![image](https://github.com/YiVal/YiVal/assets/31295352/17255ce2-49e5-4267-9266-b97a3d1581a2)

**Comment by uni-zhuan** [comment]
solved, please check [headline_gen](https://colab.research.google.com/drive/1EYyz5NKW6xDOLZt2r9CoahY_dTGgjW0B?authuser=1#scrollTo=2hOmTIbh4k1I) and [midjourney](https://colab.research.google.com/drive/1QTS3iMwQ5bOEgKDn5DrlmZ6V0rh5APdA?authuser=1)
