### ISSUE TITLE
Hosted Yival ? 

### ISSUE THREAD

**Issue by ishaan-jaff** [YiVal/YiVal#89]
**Is your feature request related to a problem? Please describe.**
I've been using YiVal for a couple days now, are you planning on building a hosted product ? 

If yes - I'd love to help out (i'm the maintainer of LiteLLM https://github.com/BerriAI/litellm)

**Comment by ishaan-jaff** [comment]
cc @crazycth

**Comment by oliverfeng** [comment]
Hey Ishaan, 

Yes, we plan to build a hosted YiVal service. Likewise, we have incorporated litellm into our code base which helps a lot on simplifying the comparison of different LLM models.

Do you want to jump into a  call with us to talk about more on collaborations. I am also in SF bay area.
cc @Yujun-Zou 

-Tao

**Comment by ishaan-jaff** [comment]
@oliverfeng yes - getting on a call would be amazing ! 
What is your email (will follow up there) ? 

Sharing my calendly if that's simpler: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat 

I'm also in SF! would love to meet in person
